# backend/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret # Nome referenciado no deployment.yaml
  namespace: app       # Mesmo namespace do deployment do backend
type: Opaque
stringData:
  DB_USER: user123     # As credenciais que seu app.py espera
  DB_PASSWORD: senha123
